# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31cb2cec8ff72d0f9a77e48bd3f2c1fc12e84e5570014f68d4b69ffd732d54bc2c7c946661b546ca2171873cf7621833872a6fbb9d8297b926723855f34c166d

test:
  secret_key_base: 3ebef28856846941d5730bccbc8e98e32d37e4c91890d2d1a44cefba8a210e0aee35afd30dc3ae017315f11cb5f6af5a690f6c3d227950bdd7883ac7af93bfff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
